FROM tensorflow/tensorflow:latest-gpu

ARG HUGGING_FACE_TOKEN

WORKDIR /app

# Install pipenv
RUN pip install pipenv

# Copy Pipfile and Pipfile.lock
COPY Pipfile Pipfile.lock ./

# Install project dependencies
RUN pipenv install --system

# Set HF_HOME (but don't rely on it for the download)
ENV HF_HOME=/app/models/.cache

# Authenticate with Hugging Face (using build argument)
ENV HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_TOKEN

# Login to Hugging Face (CRUCIAL!)
# TODO: fix later
# RUN pipenv run transformers-cli login

# Download starcoder2 (using the token directly)
# TODO: fix later
# RUN pipenv run transformers-cli download --trust-remote-code bigcode/starcoder2-7b

COPY . .

EXPOSE 8000

CMD ["python", "llm_service.py"]