FROM node:16-alpine

WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .

# RUN npm run build

# # Use a production server like Nginx
# FROM nginx:alpine

# COPY --from=0 /app/build /usr/share/nginx/html