FROM python:3.12-slim-buster

WORKDIR /app

COPY pipfile pipfile.lock ./
RUN pip install pipenv
RUN pipenv install --system --deploy

COPY . .

# Expose the API port
EXPOSE 5000

# api.py is your Flask/FastAPI application
CMD ["python", "api.py"]  