FROM python:3.13-slim

WORKDIR /app

# Install pipenv
RUN pip install pipenv

# Copy Pipfile and Pipfile.lock
COPY Pipfile Pipfile.lock ./

# Install project dependencies
RUN pipenv install --system --deploy

COPY . .

# Expose the API port
EXPOSE 5000

# api.py is your Flask/FastAPI application
CMD ["python", "api.py"]  